development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: message_moi_production

# production: &production
#   adapter: redis
#   url: redis://10.10.3.153:6381
# development: &development
#   adapter: redis
#   url: redis://localhost:6379
# test: *development
